lib/caterpie_web/router.ex
defmodule CaterpieWeb.Router do
  use CaterpieWeb, :router

  import CaterpieWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {CaterpieWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CaterpieWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", CaterpieWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: CaterpieWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", CaterpieWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", CaterpieWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", CaterpieWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/quizzes", QuizLive.Index, :index
    live "/quizzes/new", QuizLive.Index, :new
    live "/quizzes/:id/edit", QuizLive.Index, :edit
    live "/quizzes/:id", QuizLive.Index, :show
    live "/quizzes/:id/questions", QuizLive.Index, :index_question
    live "/quizzes/:id/questions/new", QuizLive.Index, :new_question
    live "/quizzes/:id/questions/:id_q/edit", QuizLive.Index, :edit_question
  end

  scope "/", CaterpieWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/caterpie_web/views/layout_view.ex
defmodule CaterpieWeb.LayoutView do
  use CaterpieWeb, :view
end

lib/caterpie_web/templates/layout/_user_menu.html.eex
<ul class="list-reset lg:flex justify-end flex-1 items-center">
<%= if @current_user do %>
  <li> <div class="ctrp_nav_link"><%= @current_user.email %></div></li>
  <li><%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "ctrp_nav_link" %></li>
  <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "ctrp_nav_link" %></li>
<% else %>
  <li><%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "ctrp_nav_link" %></li>
  <li><%= link "Log in", to: Routes.user_session_path(@conn, :new), class: "ctrp_nav_link" %></li>
<% end %>
</ul>

lib/caterpie_web/templates/layout/app.html.eex
<main role="main" class="container mx-auto mt-24">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/caterpie_web/templates/layout/live.html.leex
<main role="main" class="container mx-auto box-border h-screen pt-24">
  <p class="bg-blue-200 rounded alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="bg-red-200 rounded alert alert-error" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/caterpie_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Caterpie", suffix: " · Caterpie" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body class="bg-yellow-100 font-sans leading-normal tracking-normal">
    <header>
      <section class="container">
        <nav role="navigation" class="flex items-center justify-between flex-wrap bg-green-600 p-6 fixed w-full z-10 top-0">
          <div class="flex items-center flex-shrink-0 text-white mr-6">
            <a class="text-white no-underline hover:text-white hover:no-underline" href="#">
              <span class="text-2xl pl-2"><i class="em em-grinning"></i> Caterpie</span>
            </a>
          </div>
          <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block pt-6 lg:pt-0">
            <ul class="list-reset lg:flex justify-end flex-1 items-center">
              <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
                <li class="mr-r3">
                  <%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "ctrp_nav_link" %>
                </li>
              <% end %>
            </ul>
            <%= render "_user_menu.html", assigns %>
          </div>
        </nav>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>